# Generated by Django 5.1 on 2024-10-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='middle_initial',
            field=models.CharField(default=' ', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_initial',
            field=models.CharField(default=' ', max_length=1),
        ),
    ]
