# Generated by Django 5.1 on 2024-11-21 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlog',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='userlog',
            name='student',
        ),
        migrations.AddField(
            model_name='userlog',
            name='section',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userlog',
            name='user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='scan_time',
            field=models.TimeField(default='01:12:35'),
        ),
        migrations.AlterField(
            model_name='classinstance',
            name='date',
            field=models.DateField(default=datetime.date(2024, 11, 22)),
        ),
        migrations.AlterField(
            model_name='rfidlogs',
            name='date',
            field=models.DateField(default=datetime.date(2024, 11, 22)),
        ),
        migrations.AlterField(
            model_name='rfidlogs',
            name='scan_time',
            field=models.TimeField(default='01:12:35'),
        ),
    ]
