# Generated by Django 5.1 on 2024-11-17 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='scan_time',
            field=models.TimeField(default='02:20:36'),
        ),
        migrations.AlterField(
            model_name='classinstance',
            name='date',
            field=models.DateField(default=datetime.date(2024, 11, 18)),
        ),
        migrations.AlterField(
            model_name='rfidlogs',
            name='scan_time',
            field=models.TimeField(default='02:20:36'),
        ),
    ]
