# Generated by Django 5.0.7 on 2024-08-14 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0002_schedule_approval_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='approval_end_time',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='approval_start_time',
        ),
    ]
