# Generated by Django 5.1 on 2024-08-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0002_userlog_delete_userlogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMAC',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('computer_name', models.CharField(max_length=255)),
                ('mac_address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserLogs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(default=' ', max_length=255)),
            ],
        ),
    ]
