# Generated by Django 5.0.7 on 2024-08-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0003_remove_schedule_approval_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='weekdays',
            field=models.CharField(choices=[('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('R', 'Thursday'), ('F', 'Friday'), ('S', 'Saturday'), ('U', 'Sunday')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
