# Generated by Django 5.0.7 on 2024-08-02 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0003_blacklist_whitelist_delete_urllist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Whitelist',
        ),
    ]
