# Generated by Django 5.0.7 on 2024-08-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0005_whitelist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogs',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='userlogs',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='userlogs',
            name='middleName',
        ),
        migrations.AddField(
            model_name='userlogs',
            name='userName',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
