# Generated by Django 5.0.7 on 2024-08-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0006_remove_userlogs_firstname_remove_userlogs_lastname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RFID', models.CharField(max_length=30, unique=True)),
                ('approved', models.IntegerField(default=0)),
            ],
        ),
    ]
