# Generated by Django 5.0.7 on 2024-08-08 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0007_macaddress_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blacklist',
        ),
        migrations.DeleteModel(
            name='Whitelist',
        ),
    ]
