# Generated by Django 5.0.7 on 2024-08-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0008_delete_blacklist_delete_whitelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Whitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
            ],
        ),
    ]
